type: 'python:3.9'

dependencies:
    python3:
        pipenv: "2022.12.19"

hooks:
    build: |
        set -eu
        pipenv install --system --deploy        

    web:
        commands:
            start: python src/main.py
